#Шлях до набору данних із звичайними та анотованими фотографіями
path: ...
#Шлях до фотографій для тренування
train: ...
#Шлях до фотографій для валідації
val: ...
# Класи пошуку
names:
  0: table_tennis_ball